name: Build & Push Runner Image

on:
  workflow_dispatch: {}     # run manually when you need to rebuild (e.g., deps changed)

permissions:
  contents: read
  packages: write           # needed to push image to GHCR

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ghcr.io/luqmaan-belim/invoice-renamer:latest
