name: Build Runner Image

on:
  workflow_dispatch: {}

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Compute lowercase repo
        id: lr
        run: echo "LOWER_REPO=${GITHUB_REPOSITORY,,}" >> $GITHUB_OUTPUT

      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          # final tag is ghcr.io/<owner>/<repo>:latest (all lowercase)
          tags: ghcr.io/${{ steps.lr.outputs.LOWER_REPO }}:latest
